runtime: nodejs20

env_variables:
  DB_HOST: '34.69.251.59' # IP pública de tu instancia de Cloud SQL
  DB_NAME: 'store'
  DB_USER: 'root'
  DB_PASSWORD: ']&0&_oGAC.zG07=['
  INSTANCE_UNIX_SOCKET: '/cloudsql/speedy-realm-436918-a1:us-central1:db-articles'